name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - trunk
  pull_request:

jobs:
  # Code linting
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint code
        uses: golangci/golangci-lint-action@v2

  # Unit testing
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15', '1.16', '1.17']
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run unit tests
        run: make test
